### ISSUE TITLE
Add README, CONTRIBUTING, and LICENSE markdown files

### ISSUE THREAD

**Issue by jevenson** [CenWIDev/CenWIDev.github.io#11]
We should add a short README about the code.

CONTRIBUTING would have instructions on how to contribute to the site.

LICENSE, I would probably recommend MIT

**Comment by jevenson** [comment]
Starting work on this

**Comment by jevenson** [comment]
Contributing file should be moved to wiki

**Comment by daniel-packard** [comment]
All agreed that contributing will remain as CONTRIBUTING.md file in repo (not in wiki) because github provides features based on existence of CONTRIBUTING.md

Closing this issue
