### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by jevenson** [CenWIDev/CenWIDev.github.io#6]
It would be great to have Google Analytics setup on this site so that the organizers can monitor traffic about the site.

**Comment by TimHess** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39484225-7', 'auto');
  ga('send', 'pageview');

</script>

**Comment by jevenson** [comment]
I got this one
