### ISSUE TITLE
Create editor config file

### ISSUE THREAD

**Issue by jevenson** [CenWIDev/CenWIDev.github.io#8]
As @TimHess suggested, we should add an editor config file so that we can be consistent with formatting, tabs vs spaces, etc.

**Comment by daniel-packard** [comment]
Any objections to just stealing the html5-boilerplate .editorconfig

https://github.com/h5bp/html5-boilerplate/blob/master/.editorconfig

**spaces 4 life**

**Comment by jevenson** [comment]
Looks good to me, only change would be to make html and json indent size to be two spaces

**Comment by jevenson** [comment]
I'd understand if we didnt do html though, because that is less common

**Comment by daniel-packard** [comment]
So 2 spaces indentation, except for HTML which we'll leave at 4? 

Sounds good to me.

**Comment by jevenson** [comment]
Opposite of that actually haha. I was suggesting making JSON and HTML be 2 spaces, leave everything else at 4. And then I said if you disagree, I'm fine with leaving HTML at 4 because using 2 is less common.
